### ISSUE TITLE
Docker image appears broken

### ISSUE THREAD

**Issue by atxbyea** [iotux/ElWiz#19]
After upgrading to the latest docker image ` tuxador/elwiz` (uploaded to dockerhub 08.04.2023) I get error messages about redis missing.

```
2023-04-17T22:11:31: PM2 log: App [elwiz:0] starting in -fork mode-
22:11:31 PM2          | App [elwiz:0] exited with code [1] via signal [SIGINT]
22:11:31 PM2          | App [elwiz:0] starting in -fork mode-
2023-04-17T22:11:31: PM2 log: App [elwiz:0] online
22:11:31 PM2          | App [elwiz:0] online
22:11:31 1|NP-prices  | Fetch prices scheduling started...
22:11:31 3|currencies | Error: Cannot find module 'redis'
22:11:31 3|currencies | Require stack:
22:11:31 3|currencies | - /app/fetch-eu-currencies.js
22:11:31 3|currencies |     at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
22:11:31 3|currencies |     at Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:81:25)
22:11:31 3|currencies |     at require (node:internal/modules/helpers:119:18)
22:11:31 3|currencies |     at Object.<anonymous> (/app/fetch-eu-currencies.js:9:26)
22:11:31 3|currencies |     at Module._compile (node:internal/modules/cjs/loader:1275:14)
22:11:31 3|currencies |     at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
22:11:31 3|currencies |     at Module.load (node:internal/modules/cjs/loader:1133:32)
22:11:31 3|currencies |     at Module._load (node:internal/modules/cjs/loader:972:12)
22:11:31 3|currencies |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
22:11:31 3|currencies |     at Module._compile (node:internal/modules/cjs/loader:1275:14) {
22:11:31 3|currencies |   code: 'MODULE_NOT_FOUND',
22:11:31 3|currencies |   requireStack: [ '/app/fetch-eu-currencies.js' ]
22:11:31 3|currencies | }
2023-04-17T22:11:31: PM2 log: App [currencies:3] exited with code [1] via signal [SIGINT]
2023-04-17T22:11:31: PM2 log: App [currencies:3] starting in -fork mode-
22:11:31 PM2          | App [currencies:3] exited with code [1] via signal [SIGINT]
22:11:31 PM2          | App [currencies:3] starting in -fork mode-
2023-04-17T22:11:31: PM2 log: App [currencies:3] online
22:11:31 PM2          | App [currencies:3] online
22:11:31 2|EU-prices  | Error: Cannot find module 'redis'
22:11:31 2|EU-prices  | Require stack:
22:11:31 2|EU-prices  | - /app/fetch-eu-prices.js
22:11:31 2|EU-prices  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
22:11:31 2|EU-prices  |     at Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:81:25)
22:11:31 2|EU-prices  |     at require (node:internal/modules/helpers:119:18)
22:11:31 2|EU-prices  |     at Object.<anonymous> (/app/fetch-eu-prices.js:9:26)
22:11:31 2|EU-prices  |     at Module._compile (node:internal/modules/cjs/loader:1275:14)
22:11:31 2|EU-prices  |     at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
22:11:31 2|EU-prices  |     at Module.load (node:internal/modules/cjs/loader:1133:32)
22:11:31 2|EU-prices  |     at Module._load (node:internal/modules/cjs/loader:972:12)
22:11:31 2|EU-prices  |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
22:11:31 2|EU-prices  |     at Module._compile (node:internal/modules/cjs/loader:1275:14) {
22:11:31 2|EU-prices  |   code: 'MODULE_NOT_FOUND',
22:11:31 2|EU-prices  |   requireStack: [ '/app/fetch-eu-prices.js' ]
22:11:31 2|EU-prices  | }
```

**Comment by iotux** [comment]
Issue solved. Now the redis module is only pulled when configured to (config.yaml ---> cacheType: redis)
